// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcMessage.proto

package com.cpcb.gs;

public final class RpcMessage {
  private RpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.ckcb.gs.RpcRequest.RequestHeader header = 1;
    boolean hasHeader();
    com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader();
    com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder();
    
    // required bytes content = 2;
    boolean hasContent();
    com.google.protobuf.ByteString getContent();
  }
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage
      implements RpcRequestOrBuilder {
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(Builder builder) {
      super(builder);
    }
    private RpcRequest(boolean noInit) {}
    
    private static final RpcRequest defaultInstance;
    public static RpcRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable;
    }
    
    public interface RequestHeaderOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 rpcId = 1;
      boolean hasRpcId();
      int getRpcId();
      
      // required int32 reqId = 2;
      boolean hasReqId();
      int getReqId();
    }
    public static final class RequestHeader extends
        com.google.protobuf.GeneratedMessage
        implements RequestHeaderOrBuilder {
      // Use RequestHeader.newBuilder() to construct.
      private RequestHeader(Builder builder) {
        super(builder);
      }
      private RequestHeader(boolean noInit) {}
      
      private static final RequestHeader defaultInstance;
      public static RequestHeader getDefaultInstance() {
        return defaultInstance;
      }
      
      public RequestHeader getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 rpcId = 1;
      public static final int RPCID_FIELD_NUMBER = 1;
      private int rpcId_;
      public boolean hasRpcId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRpcId() {
        return rpcId_;
      }
      
      // required int32 reqId = 2;
      public static final int REQID_FIELD_NUMBER = 2;
      private int reqId_;
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getReqId() {
        return reqId_;
      }
      
      private void initFields() {
        rpcId_ = 0;
        reqId_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasRpcId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasReqId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, rpcId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, reqId_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, rpcId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, reqId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable;
        }
        
        // Construct using com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          rpcId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          reqId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDescriptor();
        }
        
        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getDefaultInstanceForType() {
          return com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
        }
        
        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader build() {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader buildPartial() {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader result = new com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.rpcId_ = rpcId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.reqId_ = reqId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader) {
            return mergeFrom((com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader other) {
          if (other == com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance()) return this;
          if (other.hasRpcId()) {
            setRpcId(other.getRpcId());
          }
          if (other.hasReqId()) {
            setReqId(other.getReqId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasRpcId()) {
            
            return false;
          }
          if (!hasReqId()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                rpcId_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                reqId_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 rpcId = 1;
        private int rpcId_ ;
        public boolean hasRpcId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getRpcId() {
          return rpcId_;
        }
        public Builder setRpcId(int value) {
          bitField0_ |= 0x00000001;
          rpcId_ = value;
          onChanged();
          return this;
        }
        public Builder clearRpcId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          rpcId_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 reqId = 2;
        private int reqId_ ;
        public boolean hasReqId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getReqId() {
          return reqId_;
        }
        public Builder setReqId(int value) {
          bitField0_ |= 0x00000002;
          reqId_ = value;
          onChanged();
          return this;
        }
        public Builder clearReqId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          reqId_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcRequest.RequestHeader)
      }
      
      static {
        defaultInstance = new RequestHeader(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcRequest.RequestHeader)
    }
    
    private int bitField0_;
    // required .com.ckcb.gs.RpcRequest.RequestHeader header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader() {
      return header_;
    }
    public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // required bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    
    private void initFields() {
      header_ = com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cpcb.gs.RpcMessage.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable;
      }
      
      // Construct using com.cpcb.gs.RpcMessage.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cpcb.gs.RpcMessage.RpcRequest.getDescriptor();
      }
      
      public com.cpcb.gs.RpcMessage.RpcRequest getDefaultInstanceForType() {
        return com.cpcb.gs.RpcMessage.RpcRequest.getDefaultInstance();
      }
      
      public com.cpcb.gs.RpcMessage.RpcRequest build() {
        com.cpcb.gs.RpcMessage.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cpcb.gs.RpcMessage.RpcRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cpcb.gs.RpcMessage.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cpcb.gs.RpcMessage.RpcRequest buildPartial() {
        com.cpcb.gs.RpcMessage.RpcRequest result = new com.cpcb.gs.RpcMessage.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cpcb.gs.RpcMessage.RpcRequest) {
          return mergeFrom((com.cpcb.gs.RpcMessage.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcRequest other) {
        if (other == com.cpcb.gs.RpcMessage.RpcRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder subBuilder = com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.ckcb.gs.RpcRequest.RequestHeader header = 1;
      private com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader header_ = com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance()) {
            header_ =
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // required bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcRequest)
    }
    
    static {
      defaultInstance = new RpcRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcRequest)
  }
  
  public interface RpcResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;
    boolean hasHeader();
    com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader();
    com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder();
    
    // required bytes content = 2;
    boolean hasContent();
    com.google.protobuf.ByteString getContent();
  }
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessage
      implements RpcResponseOrBuilder {
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(Builder builder) {
      super(builder);
    }
    private RpcResponse(boolean noInit) {}
    
    private static final RpcResponse defaultInstance;
    public static RpcResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable;
    }
    
    public interface ResponseHeaderOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 reqId = 1;
      boolean hasReqId();
      int getReqId();
    }
    public static final class ResponseHeader extends
        com.google.protobuf.GeneratedMessage
        implements ResponseHeaderOrBuilder {
      // Use ResponseHeader.newBuilder() to construct.
      private ResponseHeader(Builder builder) {
        super(builder);
      }
      private ResponseHeader(boolean noInit) {}
      
      private static final ResponseHeader defaultInstance;
      public static ResponseHeader getDefaultInstance() {
        return defaultInstance;
      }
      
      public ResponseHeader getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 reqId = 1;
      public static final int REQID_FIELD_NUMBER = 1;
      private int reqId_;
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getReqId() {
        return reqId_;
      }
      
      private void initFields() {
        reqId_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasReqId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, reqId_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, reqId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable;
        }
        
        // Construct using com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          reqId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDescriptor();
        }
        
        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getDefaultInstanceForType() {
          return com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
        }
        
        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader build() {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader buildPartial() {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader result = new com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.reqId_ = reqId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader) {
            return mergeFrom((com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader other) {
          if (other == com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance()) return this;
          if (other.hasReqId()) {
            setReqId(other.getReqId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasReqId()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                reqId_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 reqId = 1;
        private int reqId_ ;
        public boolean hasReqId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getReqId() {
          return reqId_;
        }
        public Builder setReqId(int value) {
          bitField0_ |= 0x00000001;
          reqId_ = value;
          onChanged();
          return this;
        }
        public Builder clearReqId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          reqId_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcResponse.ResponseHeader)
      }
      
      static {
        defaultInstance = new ResponseHeader(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcResponse.ResponseHeader)
    }
    
    private int bitField0_;
    // required .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader() {
      return header_;
    }
    public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // required bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    
    private void initFields() {
      header_ = com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cpcb.gs.RpcMessage.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable;
      }
      
      // Construct using com.cpcb.gs.RpcMessage.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cpcb.gs.RpcMessage.RpcResponse.getDescriptor();
      }
      
      public com.cpcb.gs.RpcMessage.RpcResponse getDefaultInstanceForType() {
        return com.cpcb.gs.RpcMessage.RpcResponse.getDefaultInstance();
      }
      
      public com.cpcb.gs.RpcMessage.RpcResponse build() {
        com.cpcb.gs.RpcMessage.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cpcb.gs.RpcMessage.RpcResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cpcb.gs.RpcMessage.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cpcb.gs.RpcMessage.RpcResponse buildPartial() {
        com.cpcb.gs.RpcMessage.RpcResponse result = new com.cpcb.gs.RpcMessage.RpcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cpcb.gs.RpcMessage.RpcResponse) {
          return mergeFrom((com.cpcb.gs.RpcMessage.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcResponse other) {
        if (other == com.cpcb.gs.RpcMessage.RpcResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder subBuilder = com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;
      private com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader header_ = com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance()) {
            header_ =
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // required bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcResponse)
    }
    
    static {
      defaultInstance = new RpcResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RpcMessage.proto\022\013com.ckcb.gs\"\203\001\n\nRpcR" +
      "equest\0225\n\006header\030\001 \002(\0132%.com.ckcb.gs.Rpc" +
      "Request.RequestHeader\022\017\n\007content\030\002 \002(\014\032-" +
      "\n\rRequestHeader\022\r\n\005rpcId\030\001 \002(\005\022\r\n\005reqId\030" +
      "\002 \002(\005\"x\n\013RpcResponse\0227\n\006header\030\001 \002(\0132\'.c" +
      "om.ckcb.gs.RpcResponse.ResponseHeader\022\017\n" +
      "\007content\030\002 \002(\014\032\037\n\016ResponseHeader\022\r\n\005reqI" +
      "d\030\001 \002(\005B\031\n\013com.cpcb.gsB\nRpcMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ckcb_gs_RpcRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ckcb_gs_RpcRequest_descriptor,
              new java.lang.String[] { "Header", "Content", },
              com.cpcb.gs.RpcMessage.RpcRequest.class,
              com.cpcb.gs.RpcMessage.RpcRequest.Builder.class);
          internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor =
            internal_static_com_ckcb_gs_RpcRequest_descriptor.getNestedTypes().get(0);
          internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor,
              new java.lang.String[] { "RpcId", "ReqId", },
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.class,
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder.class);
          internal_static_com_ckcb_gs_RpcResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ckcb_gs_RpcResponse_descriptor,
              new java.lang.String[] { "Header", "Content", },
              com.cpcb.gs.RpcMessage.RpcResponse.class,
              com.cpcb.gs.RpcMessage.RpcResponse.Builder.class);
          internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor =
            internal_static_com_ckcb_gs_RpcResponse_descriptor.getNestedTypes().get(0);
          internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor,
              new java.lang.String[] { "ReqId", },
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.class,
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
